import Head from 'next/head'
import FeaturedProducts from '../components/FeaturedProducts'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import NavBar from '../components/NavBar'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <NavBar/>
    <Hero/>
    <FeaturedProducts/>
    <Footer/>
    </div>
  )
}
